config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'home/contact'

  post 'markdown/preview'

  get 'chapters/show'

  get 'persons/profile'

  get 'tags/:tag', to: 'books#show', as: :tag

  resources :books do
    resources :chapters do
      resources :anotations
    end
  end

  devise_for :users
  get 'persons/profile', as: 'user_root' 

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	ratyrate_rateable "rating"
	
	belongs_to :user
	belongs_to :category
	has_many :chapters, dependent: :destroy
	acts_as_taggable

	paginates_per 5
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html, :xml, :json
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:index]
  before_action :check_book_belongs_to_user, only: [:edit, :create, :destroy, :update]

  def index
    if params[:category_id]
      @category_id = params[:category_id].to_i
      @books = Book.where(category_id: params[:category_id]).page(params[:page]).per(params[:per])
    elsif params[:tag]
      @books = Book.tagged_with(params[:tag]).page(params[:page]).per(params[:per])
    elsif params[:search]
      @books = Book.where("name like ? or description like ?","%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(params[:per])
    else
      @books = Book.page(params[:page]).per(params[:per])
    end
    respond_with(@books)
  end

  def show
    @chapter = Book.find(params[:id]).chapters.first
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit       
  end

  def create
    @book = current_user.books.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)    
  end

  def destroy
    @book.destroy
    redirect_to user_root_path, notice: "Book successfully deleted!"
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :description, :category_id, :tag_list)
    end

    def set_tags
      @tags = Book.tag_counts.map {|tag| {text: tag.name, weight: tag.taggings_count, link:  Rails.application.routes.url_helpers.books_path(:tag => tag.name)} }.to_json
    end

    def check_book_belongs_to_user
      redirect_to book_path(@book), alert: "You can not edit someone else's book " if @book.user_id != current_user.id
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_for_index.html.erb
<div class="list-group">
  <% @books.each do |book| %>
  	<% cache book do %>
	    <%= link_to(book_path(book), :class => 'list-group-item') do %>
	    	<div class='row'>
	    		<div class='col-md-9'>
			    	<h4 class="list-group-item-heading"><%= book.name %></h4>
			    	<h5 class="list-group-item-heading"><%= book.user.username %></h5>
			    </div>
			    <div class='col-md-3'>		    	
			    	<p class="list-group-item-heading"><b>Category: </b><%= book.category.name %></p>
			    </div>
			</div>
			<p class="list-group-item-text"><%= truncate(strip_tags(book.description), length: 340) %></p><br />
			<% if book.tag_list.any? %>
				<p class="list-group-item-text"><b>Tags:</b> <%= raw book.tag_list.map { |t| t }.join(', ') %></p> 	
			<% end %>
	    <% end %>
	 <% end %>
  <% end %>
</div>  

app/views/books/_categories.html.erb
<div class="list-group">  
    <% Category.all.each do |category| %>      
        <%= link_to "#{category.name}", books_path(:category_id => category.id), :class => ( category.id == @category_id ? "list-group-item active" : "list-group-item")  %> 
    <% end %>
</div>

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

    <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@book[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@book[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), :class => 'form-control' %>
    </div>
    <%= error_span(@book[:description]) %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            books_path, :class => 'btn btn-default' %>

<% end %>

app/views/books/_list_of_categories.html.erb
<div class='well well-sm'>
	<h4>Categories</h4>
	<%= render 'categories' %>
	<%= link_to 'Show all books', books_path, :class => 'btn btn-link btn-sm' %>
</div>

app/views/books/_search_form.html.erb
<%= form_tag('/books', method: :get) do %>
	<div class="input-group margin_top margin_bottom">
		<%= text_field_tag 'search', nil, placeholder: 'Enter search book...', class: "form-control" %>
		<span class="input-group-btn">
			<%= submit_tag 'Search', class: 'btn btn-default' %>
		</span>
	</div>
<% end %>

app/views/books/_tags_cloud.html.erb
<div class='well well-sm'>
	<h4>Tags</h4>
	<div id="myCanvasContainer">
	  <canvas width="200" height="200" id="myCanvas">
	    <p>Your browser not support tags 3d cloud!</p>
	  </canvas>
	</div>
	<div id="tags">
	  <ul>
	    <% tag_cloud Book.tag_counts, %w{s m l} do |tag, css_class| %>
			<li><%= link_to tag.name, books_path(:tag => tag.name), style: 'style="font-size: #{tag.taggings_count}pt"' %></li>
		<% end %>
	  </ul>
	</div>
</div>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="row">
	<div class="col-md-7">
		<%= paginate @books %>
	</div>
	<div class="col-md-5">		
		<%= render 'search_form' %>
	</div>
</div>

<div class="row">
	<div class='col-md-9'>
		<%= render 'books_for_index' %>
	</div>
	<div class='col-md-3'>
		<%= render 'list_of_categories' %>
		<%= render 'tags_cloud' %>
	</div>
</div>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<div class="page-header">
  <h1><%= @book.name.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <% if current_user == @book.user %> 
    <dt><strong> Edit book information:</strong></dt>
    <dd>
      <div class="btn-group">
        <%= link_to 'Edit', edit_book_path(@book), :class => 'btn btn-default btn-xs' %>
        <%= link_to 'Delete this book', book_path(@book), method: :delete, :class => 'btn btn-danger btn-xs', data: {confirm: 'Are you sure?'} %>
      </div>
    </dd>
  <% end %>
  <dt><strong> Author:</strong></dt>
  <dd><%= @book.user.username %></dd>
  <dt><strong> Rating of the book:</strong></dt>
  <dd><%= rating_for @book, "rating", :disable_after_rate => true %></dd>
  <dt><strong>Category:</strong></dt>
  <dd><%= @book.category.name %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= @book.description %></dd>
  <dt><strong>Tags:</strong></dt>
  <dd>
    <% if @book.tag_list.any? %>
      <%= raw @book.tag_list.map { |t| link_to t, books_path(:tag => t) }.join(', ') %>
    <% else %>
      <p>This book hasn't any tags. </p>
    <% end %>
  </dd>
  <% if current_user == @book.user %>
    <% if @book.chapters.empty? %>
      <dt><strong>Add your first chapter:</strong></dt>
      <dd><%= link_to 'Add chapter', new_book_chapter_path(@book), :class => 'btn btn-default btn-xs' %><dd>
    <% else %>
      <dt class='margin_bottom'><strong>Add chapter:</strong></dt>
      <dd><%= link_to 'Add chapter', new_book_chapter_path(@book), :class => 'btn btn-default btn-xs' %><dd>      
    <% end %>    
  <% end %>
  <% if @book.chapters.any? %>
    <dt><strong>Chapters:</strong></dt>
    <dd><%= render 'chapters/list_of_chapters' %></dd>
  <% else %>
    <dt><strong>Chapters:</strong></dt>
    <dd>This book hasn't any chapters.</dd>
  <% end %>
</dl>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                    books_path, :class => 'btn btn-default'  %>
  </div>
  <% if @book.chapters.any? %>
    <div class="col-md-2">   
        <%= link_to 'Read book', book_chapter_path(@book, @chapter), :class => 'btn btn-default' %> 
    </div>
  <% end %>
</div>