config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'home/contact'

  post 'markdown/preview'

  get 'chapters/show'

  get 'persons/profile'

  get 'tags/:tag', to: 'books#show', as: :tag

  resources :books do
    resources :chapters do
      resources :anotations
    end
  end

  devise_for :users
  get 'persons/profile', as: 'user_root' 

  root 'books#index'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :anotations, dependent: :destroy
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  respond_to :html, :xml, :json
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_action :set_book
  before_action :check_chapter_belongs_to_user, only: [:edit, :create, :destroy, :update]

  def index
    respond_with(@chapter)
  end

  def show
    @anotations = @chapter.anotations.where(:user_id => current_user)
    
    @chapters = @book.chapters

    @chapter_id = params[:id].to_i
    @first_chapter_id_of_the_book = @book.chapters.pluck(:id).first
    @last_chapter_id_of_the_book  = @book.chapters.pluck(:id).last

    chapter_index = @chapters.index(@chapter)
    (chapter_index < @chapters.length - 1) ? @next_chapter = @chapters.at(chapter_index + 1) : @next_chapter = @chapter
    (chapter_index > 0) ? @prev_chapter = @chapters.at(chapter_index - 1) : @prev_chapter = @chapter
    respond_with(@chapter)
  end

  def new
    @chapter = Chapter.new
    respond_with(@chapter)
  end

  def create
    @chapter = @book.chapters.create(chapter_params)
    redirect_to book_chapter_path(@book, @chapter)
  end

  def update
    respond_to do |format|
      if @chapter.update_attributes(chapter_params)
        format.html { redirect_to book_chapter_path(@book, @chapter), notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_with(@chapter)
  end

  def destroy
    @chapter.destroy
    redirect_to book_path(@book), notice: "Chapter successfully deleted!"
  end

  private
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def chapter_params
      params.require(:chapter).permit(:name, :content)
    end

    def set_prev_next_chapters(first_chapter_id, last_chapter_id)
      if @chapter_id < @last_chapter_id_of_the_book
        next_chapter = @chapter_id + 1
      else
        next_chapter = @chapter_id
      end
      if @chapter_id > @first_chapter_id_of_the_book
        prev_chapter = @chapter_id - 1
      else
        prev_chapter = @chapter_id
      end
    end

    def check_chapter_belongs_to_user
      redirect_to book_chapter_path(@book, @chapter), alert: "You can not edit someone else's book " if @book.user_id != current_user.id
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_display_chapter.html.erb
<h2><%= @chapter.name %></h1>
<div>
		<p>
			<%= markdown(@chapter.content) %>
		</p>
</div>

app/views/chapters/_form.html.erb
<%= form_for [@book, @chapter], :html => { :class => "form-horizontal chapter" } do |f| %>

    <% if @chapter.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@chapter.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @chapter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@chapter[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'form-control', rows: 8 %>
    </div>
    <%= error_span(@book[:content]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            books_path, :class => 'btn btn-default' %>

<% end %>

app/views/chapters/_list_of_chapters.html.erb
<div class="list-group">  
    <% @book.chapters.each do |chapter| %>      
        <%= link_to "#{chapter.name}", book_chapter_path(@book, chapter), :class => ( chapter.id == @chapter_id ? "list-group-item active" : "list-group-item")  %>        
    <% end %>
</div>

app/views/chapters/_pager_for_chapters.html.erb
<ul class="pager">
  	<li class="previous <%= 'disabled' if @chapter_id == @first_chapter_id_of_the_book %>"><%= link_to "Previous chapter", book_chapter_path(@book, @prev_chapter) %></li>
  	<li class="next <%= 'disabled' if @chapter_id == @last_chapter_id_of_the_book %>"><%= link_to "Next chapter", book_chapter_path(@book, @next_chapter) %></li>
</ul>

app/views/chapters/_tools_for_this_user.html.erb
<% if current_user == @book.user %>
	<div class="btn-group">
		<%= link_to 'Add chapter', new_book_chapter_path, :class => 'btn btn-default btn-sm' %>
		<%= link_to 'Edit chapter', edit_book_chapter_path(@book, @chapter), :class => 'btn btn-default btn-sm' %>
	</div>
		<%= link_to 'Delete this chapter', book_chapter_path(@book, @chapter), method: :delete, :class => 'btn btn-danger btn-xs', data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/chapters/edit.html.erb
<%= render 'form' %>

app/views/chapters/new.html.erb
<h2>New chapter</h2>
<%= render 'form' %>

app/views/chapters/show.html.erb
<div class="page-header">
  	<h1><%= @book.name %></h1>
</div>

<div class='row'>
	<div class="col-md-3">
		<div class="well well-sm">
			<%= render 'list_of_chapters' %>
			<%= render 'tools_for_this_user' %>
		</div>
	</div>
	<div class="col-md-8">
		<div class='well well-sm'>
			<%= render 'display_chapter' %>
			<%= render 'pager_for_chapters' %>
		</div>
		
		<% if current_user %>
				<h3>Your annotations for this chapter</h3>
				<%= render 'anotations/show_user_anotations' %>
			<h3>Add anotation</h3>
			<%= render 'anotations/new_anotation' %>
		<% else %>
			<%= link_to 'Log in for be able leave anotations', new_user_registration_path, :class => 'btn btn-link' %>
		<% end %>		
	</div>
</div>