config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'home/contact'

  post 'markdown/preview'

  get 'chapters/show'

  get 'persons/profile'

  get 'tags/:tag', to: 'books#show', as: :tag

  resources :books do
    resources :chapters do
      resources :anotations
    end
  end

  devise_for :users
  get 'persons/profile', as: 'user_root' 

  root 'books#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
        can :access, :rails_admin   # grant access to rails_admin
        can :dashboard              # grant access to the dashboard
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/anotation.rb
class Anotation < ActiveRecord::Base
  belongs_to :chapter
  belongs_to :user
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ActiveRecord::Base
	ratyrate_rateable "rating"
	
	belongs_to :user
	belongs_to :category
	has_many :chapters, dependent: :destroy
	acts_as_taggable

	paginates_per 5
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :anotations, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_many :books
  has_many :anotations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater

  LAYOUTS = [['White', 1], ['Black', 2]]

  def active_for_authentication? 
    super && !blocked?
  end 

  def inactive_message 
    if blocked? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html, :xml, :json
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:index]
  before_action :check_book_belongs_to_user, only: [:edit, :create, :destroy, :update]

  def index
    if params[:category_id]
      @category_id = params[:category_id].to_i
      @books = Book.where(category_id: params[:category_id]).page(params[:page]).per(params[:per])
    elsif params[:tag]
      @books = Book.tagged_with(params[:tag]).page(params[:page]).per(params[:per])
    elsif params[:search]
      @books = Book.where("name like ? or description like ?","%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(params[:per])
    else
      @books = Book.page(params[:page]).per(params[:per])
    end
    respond_with(@books)
  end

  def show
    @chapter = Book.find(params[:id]).chapters.first
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit       
  end

  def create
    @book = current_user.books.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)    
  end

  def destroy
    @book.destroy
    redirect_to user_root_path, notice: "Book successfully deleted!"
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :description, :category_id, :tag_list)
    end

    def set_tags
      @tags = Book.tag_counts.map {|tag| {text: tag.name, weight: tag.taggings_count, link:  Rails.application.routes.url_helpers.books_path(:tag => tag.name)} }.to_json
    end

    def check_book_belongs_to_user
      redirect_to book_path(@book), alert: "You can not edit someone else's book " if @book.user_id != current_user.id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
  end
end

app/helpers/anotations_helper.rb
module AnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
	    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
	    options = {
	        autolink: true,
	        no_intra_emphasis: true,
	        fenced_code_blocks: true,
	        lax_html_blocks: true,
	        strikethrough: true,
	        superscript: true,
	        space_after_headers: true
	    }
	    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrainProject" %></title>
    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'WritersCommunity', books_path, :class => 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse row">
          <div class='col-md-6'>
            <ul class="nav navbar-nav">
              <li><%= link_to "Main", books_path  %></li>
              <li><%= link_to "Contacts", home_contact_path  %></li>
              
            </ul>
          </div>
          <div class='col-md-4'>
            <% if current_user %>
              <div class='btn-group'>
                <%= link_to current_user.username, persons_profile_path, :class =>'btn btn-default navbar-btn btn-xs' %>
                <%= link_to "Logout" , destroy_user_session_path, method: :delete, :class =>'btn btn-default navbar-btn btn-xs' %>
              </div>
            <% else %>
              <div class='btn-group'>
                <%= link_to "Sign up", new_user_registration_path, :class =>'btn btn-default navbar-btn btn-xs'  %>
                <%= link_to "Log in", new_user_session_path, :class =>'btn btn-default navbar-btn btn-xs' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-2">
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/black.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrainProject" %></title>
    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='black'>
      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'WritersCommunity', books_path, :class => 'navbar-brand' %>
          <div class="navbar-collapse collapse navbar-responsive-collapse row">
            <div class='col-md-6'>
              <ul class="nav navbar-nav">
                <li><%= link_to "Main", books_path  %></li>
                <li><%= link_to "Contacts", home_contact_path  %></li>
                
              </ul>
            </div>
            <div class='col-md-4'>
              <% if current_user %>
                <div class='btn-group'>
                  <%= link_to current_user.username, persons_profile_path, :class =>'btn btn-default navbar-btn btn-xs' %>
                  <%= link_to "Logout" , destroy_user_session_path, method: :delete, :class =>'btn btn-default navbar-btn btn-xs' %>
                </div>
              <% else %>
                <div class='btn-group'>
                  <%= link_to "Sign up", new_user_registration_path, :class =>'btn btn-default navbar-btn btn-xs'  %>
                  <%= link_to "Log in", new_user_session_path, :class =>'btn btn-default navbar-btn btn-xs' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-10">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="col-lg-2">
          </div><!--/span-->
        </div><!--/row-->

        <footer>
          <p>&copy; Company 2014</p>
        </footer>

      </div> <!-- /container -->
    </div>
  </body>
</html>

app/views/layouts/boot_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrainProject" %></title>
    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'WritersCommunity', books_path, :class => 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse row">
          <div class='col-md-6'>
            <ul class="nav navbar-nav">
              <li><%= link_to "Main", books_path  %></li>
              <li><%= link_to "Contacts", home_contact_path  %></li>
              
            </ul>
          </div>
          <div class='col-md-4'>
            <% if current_user %>
              <div class='btn-group'>
                <%= link_to current_user.username, persons_profile_path, :class =>'btn btn-default navbar-btn btn-xs' %>
                <%= link_to "Logout" , destroy_user_session_path, method: :delete, :class =>'btn btn-default navbar-btn btn-xs' %>
              </div>
            <% else %>
              <div class='btn-group'>
                <%= link_to "Sign up", new_user_registration_path, :class =>'btn btn-default navbar-btn btn-xs'  %>
                <%= link_to "Log in", new_user_session_path, :class =>'btn btn-default navbar-btn btn-xs' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-2">
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>